---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: '11/2/2021'
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Sahith Kasireddy, sk48663

#### Introduction 

My two datasets deal with data related to countries. One dataset, hif, is about the different examples of freedom from political scientists. The other dataset, renamed to UNImmigration, deals with the number of people leaving a country to a different country. I am interested in this dataset because I am really interested in cultures and the social and political systems of countries. The hfi dataset was found from a list of common packaged datasets found in the Project1 Instructions link. The data for the UNImmigration was also found in one of the links but had to be manually repackaged by me in order to become a csv file.

I believe that there will be a positive correlation between the number of people entering a country and a country's overall human freedex index score as well as its individual index scores. Therefore, I would also believe that there would be a negative correlation between the number of people leaving a country and the country's overall human freedom index score as well as its individual index scores. I am also interested in varying data between the top countries of a certain category and the worst countries of a certain category. 

```{R}
library(dplyr)
library(tidyverse)
hfi <- read.csv(file = 'hfi.csv')
UNImmigration <- read.csv(file ='CountryDataSet2.0.csv')

```

#### Tidying: Reshaping


```{R}
#Renaming variable, removing uneeded columns, and snapshot of sample
UNImmigration<- UNImmigration %>% rename("Country/Region of Destination" = Major.area..region..country.or.area.of.destination) %>% select(-c(1,3, 5:10)) 
UNImmigration %>% select(3:13) %>% slice(100:110)

#Filtering out uneeded observations and snapshot of sample after tidying
UNImmigration <- UNImmigration %>% pivot_longer(3:234, names_to="Country of Origin", values_to="Number of People Immigrating Out of Country")
UNImmigration <- UNImmigration %>% filter(`Country of Origin`!="Total" & `Country of Origin`!="Other North" & `Country of Origin`!="Other South")
UNImmigration %>% slice(2000, 75000, 100000, 254000, 400000)

```
One of the variables was renamed to 'Country/Region of Destination', which are the regions or countries that migrants are immigrating to. Extraneous columns were removed from the 'UNImmigration' dataset because they either do not have numerical value or will not be used later. The first headshot shows some observations of the data before tidying. Each individual country is its own variable as seen at the top of the headshot, which shows a sample of some of the countries. 

After tidying (pivot_longer) the dataset, columns 3 through 234 were selected from the 'UNImmigration dataset.' These countries became essentially combined into a column titled "Country of Origin" which are the countries in the dataset that migrants are migrating from. The numerical values under the untidied dataset were put under a column titled "Number of People Immigrating Out Country." Some observations were filtered out because they are total values and will not be used further. A headhsot of randomly picked observations from the tidied 'UNImmigration dataset' were picked.

    
#### Joining/Merging

```{R}
#Filtering out many extraneous regions, such as categories of development and continents. Only actual countries wanted actual countries. 
UNImmigration<- UNImmigration %>% filter(`Country/Region of Destination`!="UN development groups" & `Country/Region of Destination`!="World Bank income groups" & `Country/Region of Destination`!="Geographic regions" & `Country/Region of Destination`!="WORLD" & `Country/Region of Destination`!="More developed regions" & `Country/Region of Destination`!="Less developed regions" & `Country/Region of Destination`!="Least developed countries" & `Country/Region of Destination`!="Less developed regions, excluding least developed countries" & `Country/Region of Destination`!="High-income countries" & `Country/Region of Destination`!="Middle-income countries" & `Country/Region of Destination`!="Upper-middle-income countries" & `Country/Region of Destination`!="Lower-middle-income countries" & `Country/Region of Destination`!="Low-income countries" & `Country/Region of Destination`!="No income group available" & `Country/Region of Destination`!="Sustainable Development Goal (SDG) regions")

UNImmigration <- UNImmigration %>% filter(`Country/Region of Destination`!="Africa" & `Country/Region of Destination`!="Asia" & `Country/Region of Destination`!="Caribbean" & 
`Country/Region of Destination`!="Central America"& `Country/Region of Destination`!="Central Asia" & `Country/Region of Destination`!="Eastern Africa" & `Country/Region of Destination`!="Western Europe" & 
`Country/Region of Destination`!="Africa" & `Country/Region of Destination`!="Asia" & `Country/Region of Destination`!="Central America"& `Country/Region of Destination`!="Central Asia" & 
`Country/Region of Destination`!="Eastern Africa" & `Country/Region of Destination`!="Western Europe" & `Country/Region of Destination`!="CENTRAL AND SOUTHERN ASIA" & 
`Country/Region of Destination`!="EASTERN AND SOUTH-EASTERN ASIA" & `Country/Region of Destination`!="Eastern Asia"& `Country/Region of Destination`!="Eastern Europe" & 
`Country/Region of Destination`!="Europe" & `Country/Region of Destination`!="EUROPE" & `Country/Region of Destination`!="Australia / New Zealand" & `Country/Region of Destination`!="EUROPE AND NORTHERN AMERICA" & 
`Country/Region of Destination`!="Latin America and the Caribbean" & `Country/Region of Destination`!="LATIN AMERICA AND THE CARIBBEAN" & `Country/Region of Destination`!="Asia" & 
`Country/Region of Destination`!="Middle Africa" & `Country/Region of Destination`!="Northern Africa" & `Country/Region of Destination`!="NORTHERN AFRICA AND WESTERN ASIA" & 
`Country/Region of Destination`!="Northern America" & `Country/Region of Destination`!="NORTHERN AMERICA" & `Country/Region of Destination`!="Northern Europe" & `Country/Region of Destination`!="OCEANIA" & 
`Country/Region of Destination`!="Oceania" & `Country/Region of Destination`!="South America" & `Country/Region of Destination`!="South-Eastern Asia" & `Country/Region of Destination`!="Southern Africa" & 
`Country/Region of Destination`!="Southern Asia" & `Country/Region of Destination`!="Southern Europe" & `Country/Region of Destination`!="SUB-SAHARAN AFRICA" & `Country/Region of Destination`!="Western Africa" & 
`Country/Region of Destination`!="Western Asia")

#Regex to rename countries from UNImmigration dataset
UNImmigration<- UNImmigration %>% mutate(`Country of Origin`=str_replace_all(`Country of Origin`, "\\.", " ")) 

UNImmigration$`Country of Origin` <- str_replace_all(UNImmigration$`Country of Origin`, c("Bolivia  Plurinational State of" ="Bolivia", "Central African Republic" ="Central Afr. Rep.", "Cabo Verde" ="Cape Verde", "Congo" ="Congo, Rep. Of", "Democratic Republic of the Congo" ="Congo, Dem. R.", "China Hong Kong SAR" ="Hong Kong", "Czechia" ="Czech Rep.", "Dominican Republic" ="Dominican Rep.", "Gambia"= "Gambia, The", "Guinea Bissau"="Guinea-Bissau", "Iran  Islamic Republic of" ="Iran", "Lao People s Democratic Republic" ="Laos", "Republic of Korea" ="Korea, South", "Kyrgyzstan" ="Kyrgyz Republic", "Papua New Guinea" ="Pap. New Guinea", "Republic of Moldova" ="Moldova", "Russian Federation" ="Russia", "Slovakia"="Slovak Rep.", "Syrian Arab Republic" ="Syria", "Timor Leste" ="Timor-Leste", "United Republic of Tanzania" ="Tanzania", "United States of America" ="United States", "Venezuela  Bolivarian Republic of" ="Venezuela", "Viet Nam" ="Vietnam", "Yemen" ="Yemen, Rep.", "Eswatini" ="Swaziland"))


UNImmigration$`Country of Origin` <-str_replace_all(UNImmigration$`Country of Origin`, c("Bolivia "="Bolivia","China  Hong Kong SAR"="Hong Kong", "Iran "="Iran", "Venezuela "= "Venezuela", "Congo, Dem. R., Rep. Of" ="Congo, Dem. R."))

UNImmigration<- UNImmigration %>% mutate(`Country/Region of Destination`=str_replace_all(`Country/Region of Destination`, "\\.", " ")) 

UNImmigration$`Country/Region of Destination` <- str_replace_all(UNImmigration$`Country/Region of Destination`, c("Bolivia  Plurinational State of" ="Bolivia", "Central African Republic" ="Central Afr. Rep.", "Cabo Verde" ="Cape Verde", "Congo" ="Congo, Rep. Of", "Democratic Republic of the Congo" ="Congo, Dem. R.", "China, Hong Kong SAR" ="Hong Kong", "Czechia" ="Czech Rep.", "Dominican Republic" ="Dominican Rep.", "Gambia"= "Gambia, The", "Guinea Bissau"="Guinea-Bissau", "Iran  Islamic Republic of" ="Iran", "Lao People s Democratic Republic" ="Laos", "Republic of Korea" ="Korea, South", "Kyrgyzstan" ="Kyrgyz Republic", "Papua New Guinea" ="Pap. New Guinea", "Republic of Moldova" ="Moldova", "Russian Federation" ="Russia", "Slovakia"="Slovak Rep.", "Syrian Arab Republic" ="Syria", "Timor Leste" ="Timor-Leste", "United Republic of Tanzania" ="Tanzania", "United States of America" ="United States", "Venezuela(Bolivarian Republic of)" ="Venezuela", "Viet Nam" ="Vietnam", "Yemen" ="Yemen, Rep.", "Eswatini" ="Swaziland"))

UNImmigration$`Country/Region of Destination` <-str_replace_all(UNImmigration$`Country/Region of Destination`, c("Bolivia "="Bolivia","China  Hong Kong SAR"="Hong Kong", "Iran "="Iran", "Congo, Dem. R., Rep. Of" ="Congo, Dem. R."))

#Cleaning up hfi
hfi <- hfi %>% rename("Country of Origin" = `countries`, "Year" = year) %>% select(-c(1,3))

#Calculating number of observations for both datasets right before joining
UNImmigration %>% count()
hfi %>% count()

#Inner join and its analysis conducted
joinedDataSet <- inner_join(UNImmigration, hfi, by=c("Country of Origin","Year"))

joinedDataSet %>% count()

#Calculating the number of observations that were dropped after joining
381640 - 72380

#install.packages("arsenal")
library(arsenal)


comparedf(x = hfi %>% slice(-(1:1458)) %>% select(c(1:3), pf_religion, pf_identity_sex, pf_rol_procedural, pf_ss_disappearances_disap, pf_movement_women, pf_association_association, pf_association_assembly, pf_expression, pf_identity_divorce,ef_regulation, hf_score), y = UNImmigration %>% slice(-(1:381640)))


summary(comparedf(hfi %>% slice(-(1:1458)) %>% select(c(1:3), pf_religion, pf_identity_sex, pf_rol_procedural, pf_ss_disappearances_disap, pf_movement_women, pf_association_association, pf_association_assembly, pf_expression, pf_identity_divorce,ef_regulation, hf_score), UNImmigration %>% slice(-(1:381640))))

```
After filtering out unneeded regions from both the 'Country/Region of Destination' varible and the 'Country of Origin' variable in the UNImmigration dataset, Regex (regular expressions) were used to make sure that the common countries between the two datasets were spelled the same. The two unique ID variables in the UNImmigration dataset: 'Country of Destination' and "Number of People Immigrating Out of Country". The unique ID variables in the hfi dataset are numerous. There are 120 unique variables of 122 variables (only 'Year' and 'Country of Origin' are not unique). Some of the unique ID variables in the 'hif' that I will be using are 'pf_religion, pf_identity_sex, pf_rol_procedural, pf_ss_disappearances_disap, pf_movement_women, pf_association_association, pf_association_assembly, pf_expression, pf_identity_divorce,ef_regulation, and hf_score' (All of this is shown in the summary of the compare data frame code of the datasets, that were very filtered, for simplicity sake).

An inner join was performed in order to match the data values from the UNImmigration dataset to the hfi dataset. An inner join was performed instead of other types of joins in order to keep data that only matched, , which meant that 309260 observations were dropped, considering that there were 72380 observations in the joinedDataSet. This will not create an issue for my analyssi because I only wanted data that was matched between both sets to make analysis consistent. Additionally, because I will be using variables from both datasets in my graphs, I did not want there to be data accounted for in that graph that did not come from both sets.

####  Wrangling

```{R}
#Making blank or observatiosn with .. into NA, selecting only interested variables, and filtering out rows with just NA for all numerical data. 
joinedDataSet<- joinedDataSet %>% mutate_all(na_if,"")
joinedDataSet<- joinedDataSet %>% mutate_all(na_if,"..")

joinedDataSet <- joinedDataSet %>% select(c(1:5), pf_religion, pf_identity_sex, pf_rol_procedural, pf_ss_disappearances_disap, pf_movement_women, pf_association_association, pf_association_assembly, pf_expression, pf_identity_divorce,ef_regulation, hf_score)

joinedDataSet<- joinedDataSet%>%filter(!if_all(c(4, 6:16), is.na))

#New variable created
joinedDataSet$`Number of People Immigrating Out of Country` <- as.integer(joinedDataSet$`Number of People Immigrating Out of Country`)

joinedDataSet<- joinedDataSet %>% arrange(`Country of Origin`, `Country/Region of Destination`, Year) %>% mutate(ChangeInImmigration = (`Number of People Immigrating Out of Country`-lag(`Number of People Immigrating Out of Country`)) /lag(`Number of People Immigrating Out of Country`))

#Number of NAs in each column
NumberofNAs<- joinedDataSet %>% summarize_all(function(x)sum(is.na(x))) 

justnumeric <- joinedDataSet %>% select(4:17)


justnumeric %>% summarize_all(function(x)mean(x, na.rm = T))


NumberofNAs <- NumberofNAs %>% pivot_longer(1:17, names_to="Variables", values_to="Number of NA values")
NumberofNAs 

#Freqeuncy of Each Categorical Variable
joinedDataSet %>% group_by(`Country/Region of Destination`) %>% summarise(Count = n())
joinedDataSet %>% group_by(`Country of Origin`) %>% summarise(Count= n())
joinedDataSet %>% group_by(`Year`) %>% summarise(Count = n())

#SummaryStatistic Not Accounting for Any Categorical Variable
SSNumerical<- joinedDataSet %>% summarise_at(c(4, 6:17), .funs = list(mean=mean, sd=sd, median=median, min=min, max=max), na.rm = TRUE) %>% pivot_longer(c(1:65))

SSNumerical<- SSNumerical %>% mutate(`name`=str_replace_all(`name`, "pf_re", "pf re")) %>% mutate(`name`=str_replace_all(`name`, "pf_identity_s", "pf identity s")) %>% mutate(`name`=str_replace_all(`name`, "pf_rol_pro", "pf rol pro")) %>% mutate(`name`=str_replace_all(`name`, "pf_ss_disappearances_d", "pf ss disappearances d")) %>% mutate(`name`=str_replace_all(`name`, "pf_movement_w", "pf movement w")) %>% mutate(`name`=str_replace_all(`name`, "pf_association_ass", "pf association ass"))  %>% mutate(`name`=str_replace_all(`name`, "pf_ex", "pf ex")) %>% mutate(`name`=str_replace_all(`name`, "pf_identity_divorce", "pf identity divorce")) %>% mutate(`name`=str_replace_all(`name`, "hf_score", "hf score")) %>% mutate(`name`=str_replace_all(`name`, "ef_regulation", "ef regulation"))

SSNumerical <- SSNumerical %>% separate(name, into=c("name","stat"), sep="_") %>% pivot_wider() %>% rename("Number of People Immigrating From One Country to Another"=`Number of People Immigrating Out of Country`)

#Summary Statistic Accounting for Country of Origin as a Categorical Variable
SSOneCat<- joinedDataSet %>% group_by(`Country of Origin`) %>% summarise_at(c(3, 5:16), .funs = list(mean=mean, sd=sd, median=median, min=min, max=max), na.rm = TRUE) %>% pivot_longer(-1) 

SSOneCat<- SSOneCat %>% mutate(`name`=str_replace_all(`name`, "pf_re", "pf re")) %>% mutate(`name`=str_replace_all(`name`, "pf_identity_s", "pf identity s")) %>% mutate(`name`=str_replace_all(`name`, "pf_rol_pro", "pf rol pro")) %>% mutate(`name`=str_replace_all(`name`, "pf_ss_disappearances_d", "pf ss disappearances d")) %>% mutate(`name`=str_replace_all(`name`, "pf_movement_w", "pf movement w")) %>% mutate(`name`=str_replace_all(`name`, "pf_association_ass", "pf association ass"))  %>% mutate(`name`=str_replace_all(`name`, "pf_ex", "pf ex")) %>% mutate(`name`=str_replace_all(`name`, "pf_identity_divorce", "pf identity divorce")) %>% mutate(`name`=str_replace_all(`name`, "hf_score", "hf score")) %>% mutate(`name`=str_replace_all(`name`, "ef_regulation", "ef regulation"))
SSOneCat <- SSOneCat %>% separate(name, into=c("name","stat"), sep="_") %>% pivot_wider()

SSOneCat %>% filter(stat=="max") %>% arrange(desc(`Number of People Immigrating Out of Country`))
SSOneCat %>% filter(stat=="max") %>% arrange(`Number of People Immigrating Out of Country`)
SSOneCat %>% filter(stat=="min") %>% arrange(`Number of People Immigrating Out of Country`) %>% filter(`Number of People Immigrating Out of Country`==3) %>% count()

joinedDataSet %>% arrange(desc(`Number of People Immigrating Out of Country`))


#Total Number of Immigrants
joinedDataSet %>% filter(!is.na(`Number of People Immigrating Out of Country`)) %>% summarise("Sum" = sum(`Number of People Immigrating Out of Country`))
  
#Creating a Function
percentofTotal<- function(x)((x/112908006) * 100)


#Summary Statistic Accounting for Two Categorical Variables: Country/Region of Destination and Year
 
SSTwoCat<- joinedDataSet %>% group_by(`Country/Region of Destination`, Year) %>% filter(!is.na(`Number of People Immigrating Out of Country`)) %>% summarise("Number Of People Immigrating Into Country" = sum(`Number of People Immigrating Out of Country`)) %>% mutate("PercentOutofTotalEmigrants" = percentofTotal(`Number Of People Immigrating Into Country`)) 

SSTwoCat %>% arrange(desc(PercentOutofTotalEmigrants))

library(kableExtra)
#install.packages("gt")
library(gt)

SSNumerical %>% gt
SSOneCat %>% slice(91:101) %>% gt 
SSTwoCat %>% head() %>% gt


```

Before exploring my data, I made sure to convert any blank observations or observations with .. into NA values. Afterwards, I selected only the variables of interest and created a new variable with the function "mutate" to show the percent change in immigration from and to a country between the years 2015 and 2010. The 'hf_score' variable is the total hf_score from the 'joinedDataSet' rather than my own averaged hf_score. I also found the number of NAs in each column, which varied from 0 to 56086. I also found the frequency of each level of a categorical variable as well (Year is treated as a categorical variable rather than numeric because it does not present value standalone unlike the other numeric variables). Then, I created my first summary statistic just based off of numerical values. I used many different dpylr functions to create my data. Although it was a little cumbersome, I used the str_replace function to help in preparation for the separate function for two of my tables! For one of the tables, I had used my own function that computed the percentage out of an accumulated total number of emmigrants. 

Respective summary tables were created for each numeric variable, at first, by themselves, and then paired with one, and two categorical variables. For the first summary table, it was very surprising to find that the standard deviation was much greater than the mean. This meant that some countries are really hot spot destinations for people in some countries while other countries are very rarely visited by people in another country. For the summary table that accounted for country of origin it was interesting to find that the country that had the single highest emigration to another country was Zimbabwe. It was also interesting to find that there were a lot of countries that had a minimum of just 3 people leaving to another country. In fact, there were about 146 times that this had occurred. For the summary statistic table accounting for two categorical variables, I also created my own function to use as one of the statistics in one of my summary tables. This function computes the percent of emigrants out of the total pool of emigrants from both years (not to be confused with immigrants!) This meant that the country with the highest percentage of emigrants out of the total was the United States in 2015. 

#### Visualizing

```{R}
library(ggplot2)

mu <- joinedDataSet %>% group_by(region) %>% summarize(grp.mean = mean(ef_regulation, na.rm = T))
mu

ggplot(joinedDataSet, aes(x=ef_regulation, fill=region)) +geom_density(alpha=.75) + theme(legend.position=c(.2,.6)) +
geom_vline(data = mu, aes(xintercept = grp.mean, color = region), linetype = "dashed") +
ggtitle("Density Plot of Market Regulation Scores by Region")+xlab("Regulation Scores")+ylab("Density") + scale_x_continuous(breaks=seq(0,10,0.5)) + scale_y_continuous(breaks=seq(0,8,1))

```
This density plot indicates the regulation scores for the 2015 year for different regions across the world. Furthermore, mean lines were added in order to highlight the mean for the respective regions' mean regulation scores. The countries that have higher market regulation scores are the ones that are furthest to the right. These include North America and Western Europe. Furthermore, it is evident that around a regulation score of around 7, there is some overlap between Oceania, Eastern Europe, East Asia, and Latin America, which highlights that this is a common regulation score for many countries in those regions to be around. One major outlier is how North America has a very high percentage of countreis that have a high market regulation score. This makes sense however, considering that North America is only composed of Canada and The United States. 

```{R}


joinedDataSet %>% group_by(`Country of Origin`, Year) %>% filter(!is.na(`Number of People Immigrating Out of Country`) & (!is.na(pf_religion))) %>% summarise("Total Number of People Immigrating Out of Country" = sum(`Number of People Immigrating Out of Country`))  %>% arrange(`Total Number of People Immigrating Out of Country`) %>% filter(n()>1)

joinedDataSet %>% group_by(`Country of Origin`, Year) %>% filter(!is.na(`Number of People Immigrating Out of Country`) & (!is.na(pf_religion))) %>% summarise("Total Number of People Immigrating Out of Country" = sum(`Number of People Immigrating Out of Country`))  %>% arrange(desc(`Total Number of People Immigrating Out of Country`)) %>% filter(n()>1)

                                                                                                                    Top5Low5ByNumberOfPeopleLeaving <- joinedDataSet %>% filter(!is.na(`Number of People Immigrating Out of Country`)) %>% filter(`Country of Origin`=="United States"|`Country of Origin`=="United Kingdom"|`Country of Origin`=="Russia"|`Country of Origin`=="India"|`Country of Origin`=="Philippines"|`Country of Origin`=="Botswana"|`Country of Origin`=="Albania"|`Country of Origin`=="Swaziland"|`Country of Origin`=="Bahamas"|`Country of Origin`=="Pap. New Guinea")  %>% group_by(`Country of Origin`, Year) %>% mutate("Number of People Immigrating Out of Country" = sum(`Number of People Immigrating Out of Country`))                                                                                                                                                                                                                             
                                                       
ggplot(Top5Low5ByNumberOfPeopleLeaving, aes(`Number of People Immigrating Out of Country`, pf_religion))+ geom_point(size=5, aes(color= `Country of Origin`)) + geom_line(alpha = .2) + ggtitle("Relationship between Religious Freedom and Number of People Leaving a Country")+xlab("Number of People Leaving Country")+ylab("Religion Index Score") + facet_grid(rows = vars(Year)) + scale_x_continuous(breaks=seq(0,2500000,250000)) + theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1, size=9))



```

Because I knew that I wanted to facet my data, I had to filter my data accordingly. I wanted the top 5 countries with the most immigrants and the top 5 countries with the least immigrants if they did not have missing data for the religious index score for both years (2010 and 2015), which was why the 'filter(n()>1' function was used (because some countries were bypassed because they had data for one year and not the other) I then made a new dataset for this titled 'Top5Low5ByNumberOfPeopleLeaving' by filtering the original dataset with the respective countries.

The overall pattern of the ggplot seems to change quite a bit. The top left of the plot is about the same for the number of immigrants leaving per year, althought the religious index score seems to change quite a bit for Pap. New Guiena after about 5 years. For the right half of the plot, most of the countries have around the same number of immigrants leaving for both 2010 and 2015. However, India seems to drop off quiet a bit in its religious index score. Overall, it seems like a conclusion cannot really be made about the relationship between a country's religious freedom and the number of people leaving a country. This is because for countries with around the same religious index scores as other countries can have much less number of immigrants leaving that country. It could possibly be said that relgious freedom and immigrants are independent of another. 


```{R}
joinedDataSet %>% filter(Year==2015) %>% group_by(`Country of Origin`) %>% arrange(desc(hf_score)) %>% filter(`Country/Region of Destination`=="Afghanistan") %>% select(3, 16)

joinedDataSet %>% filter(Year==2015) %>% group_by(`Country of Origin`) %>% arrange(hf_score) %>% filter(`Country/Region of Destination`=="Afghanistan") %>% select(3, 16)

RankedbyHF<- joinedDataSet %>% filter(!is.na(`Number of People Immigrating Out of Country`)) %>% filter(`Country/Region of Destination`=="Syria"|`Country/Region of Destination`=="Libya"|`Country/Region of Destination`=="Egypt"|`Country/Region of Destination`=="Venezuela (Bolivarian Republic of)"|`Country/Region of Destination`=="Yemen, Rep."|`Country/Region of Destination`=="New Zealand"|`Country/Region of Destination`=="Hong Kong"|`Country/Region of Destination`=="Switzerland"|`Country/Region of Destination`=="Ireland"|`Country/Region of Destination`=="Australia") %>% group_by(`Country/Region of Destination`) %>% filter(Year==2015) 


RankedbyHF$`Country/Region of Destination` <- str_replace_all(RankedbyHF$`Country/Region of Destination`, "(Bolivarian Republic of)", "")
RankedbyHF$`Country/Region of Destination` <- str_replace_all(RankedbyHF$`Country/Region of Destination`, "()", "")
RankedbyHF$`Country/Region of Destination` <- str_replace_all(RankedbyHF$`Country/Region of Destination`, "Yemen, Rep.", "Yemen")

ggplot(RankedbyHF, aes(x = `Country/Region of Destination`)) + geom_bar(aes(y=`Number of People Immigrating Out of Country`), stat="summary", fun=mean) + ggtitle("Mean Number of People Immigrating to the Top 5 Best and Worst Ranked Countries by Overall Freedom Index")+xlab("Countries")+ylab("Number of People Entering Country") + theme(text = element_text(size=8), axis.text.x = element_text(angle=90, hjust=1, size=7)) + scale_y_continuous(breaks=seq(0, 15000, 5000))
```

I filtered my data to find the top 5 countries with the highest overall human index score as well as the bottom 5 countries with the lowest overall human index score from the Year 2015. I then made a new dataset for this titled 'RankedbyHF' by filtering the original dataset with the respective countries. Then, using this dataset, and cleaning up names with str_replace, the ggplot of a bar graph was created. 

This bar graph shows that the country with the highest mean number of emigrants is Hong Kong while the country with the lowest mean number of emigrants is Egypt. Ireland and New Zealand are the two countries that despite having high overall Human Index scores seem to have lower emigrants than the countries with the worst overall human index scores, which was a surprise, considering that the other top HF scoring countries had higher emigrants than any low scoring country. 


#### Concluding Remarks

If any!




